In [23]:
import numpy as np


In [25]:
## Defining protocol data for Servo turn on/off

reqid=1
cdno=hex2dec('83')
inst=2
att=1
ser=hex2dec('10');
dataon=[1, 0, 0, 0];
dataoff=[2, 0, 0, 0];
dataservoon=[89, 69, 82, 67, 32, 0, 4, 0, 3, 1, 0, reqid, 0, 0, 0, 0, 57, 57, 57, 57, 57, 57, 57, 57, cdno, 0, inst, 0, att, ser, 0, 0, dataon];
dataservooff=[89, 69, 82, 67, 32, 0, 4, 0, 3, 1, 0, reqid, 0, 0, 0, 0, 57, 57, 57, 57, 57, 57, 57, 57, cdno, 0, inst, 0, att, ser, 0, 0, dataoff];

NameError: name 'hex2dec' is not defined

In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])
np.concatenate((a,b), axis=0)
np.hstack((a,b))

array([1, 2, 3, 4, 2, 3, 4, 5])

In [26]:
cdno=int('83')
cdno

83

In [31]:
np.hstack((a,cdno,b,25,33))

array([ 1,  2,  3,  4, 83,  2,  3,  4,  5, 25, 33])

In [26]:
import numpy as np


#servo on or off
def servo_motor(a):
    reqid=1
    cdno=int('83')
    inst=2
    att=1
    ser=int('10')
    dataon = np.array([1, 0, 0, 0])
    dataoff = np.array([2, 0, 0, 0])
    dataservoon = np.hstack((89, 69, 82, 67, 32, 0, 4, 0, 3, 1, 0, reqid, 0, 0, 0, 0, 57, 57, 57, 57, 57, 57, 57, 57, cdno, 0, inst, 0, att, ser, 0, 0, dataon))
    dataservooff = np.hstack((89, 69, 82, 67, 32, 0, 4, 0, 3, 1, 0, reqid, 0, 0, 0, 0, 57, 57, 57, 57, 57, 57, 57, 57, cdno, 0, inst, 0, att, ser, 0, 0, dataoff))
    if a == True:
        return dataservoon
    else:
        return dataservooff
    
#type of input givent to the code is 'a' which is a boolean varaible

In [42]:
x = servo_motor(1)
x

array([89, 69, 82, 67, 32,  0,  4,  0,  3,  1,  0,  1,  0,  0,  0,  0, 57,
       57, 57, 57, 57, 57, 57, 57, 83,  0,  2,  0,  1, 10,  0,  0,  1,  0,
        0,  0])

In [46]:
import socket
UDP_IP_ADDRESS = '192.168.255.1'
UDP_PORT_NO = 10040
Message = "Hello, Server"


import time

#to create the socket through which we will be sending our UDP message to the server
clientSock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

#clientSock.connect((UDP_IP_ADDRESS, UDP_PORT_NO))


#to write the code that will send our UDP message (turn on)
s = clientSock.sendto(servo_motor(1), (UDP_IP_ADDRESS, UDP_PORT_NO))
x = clientSock.recvmsg(1000)

time.sleep(5)# number of seconds

#to write the code that will send our UDP message (turn off)
clientSock.sendto(servo_motor(0), (UDP_IP_ADDRESS, UDP_PORT_NO))
print(x)

(b'YERC \x00\x00\x00E\x00\x01\x00\x00\x00\x00\x80R\x00\x00\x00\x00\x00\x00\x00\x80\x1f\x01\x00\xa7\xe4\x00\x00', [], 0, ('192.168.255.1', 10040))


In [69]:
np.str(x)
x[0]

SyntaxError: invalid syntax (<ipython-input-69-8e221d78f5b2>, line 1)

In [47]:
clientSock.close()

In [9]:

#to write the code that will send our UDP message (turn on)
clientSock.sendto(servo_motor(1), (UDP_IP_ADDRESS, UDP_PORT_NO))


time.sleep(5)# number of seconds

#to write the code that will send our UDP message (turn off)
clientSock.sendto(servo_motor(0), (UDP_IP_ADDRESS, UDP_PORT_NO))




OSError: [Errno 9] Bad file descriptor

In [7]:

socket.SocketKind

<enum 'SocketKind'>

In [11]:
socket.gethostname()

'agenthimzz-891.local'

In [12]:
socket.getservbyname()

TypeError: getservbyname() takes at least 1 argument (0 given)